### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by ywevanderpol** [praegus/fitnesse-bootstrap-plus-theme#13]
when validating a Fitnesse script (in this case PageObjects) there seem to be some random errors: Unknown command: value of (0 parameters)

0 can be replaced by N

![image](https://user-images.githubusercontent.com/24470599/72793952-701e6a80-3c3b-11ea-8896-7469f806ed81.png)

**This is an example that generates an error:**
`|$label_DocumentsoortEmailBelangenbehartigerTekstblokkenAvpCheckbox=|value of|Univé erkent aansprakelijkheid voor de schade die door het ongeval ontstond                                |`

**and a second one:**
`|$label_Tablet=                         |value of|Tablet                                  |`

**an example of my pageobjects file:**
[PageObjects.txt](https://github.com/praegus/fitnesse-bootstrap-plus-theme/files/4090297/PageObjects.txt)

**Comment by tcnh** [comment]
This is caused by incorrect handling of reserved words like check, table, etc. If the first cell contains these, the parameters are ignored.

Will make reserved words checking more explicit to avoid this kind of false positives
