### ISSUE TITLE
Support creating (comment) table without bold first row

### ISSUE THREAD

**Issue by fhoeben** [praegus/fitnesse-bootstrap-plus-theme#2]
While in general the bold first row of tables provided by bootstrap-plus is great in some tables I would like to disable it so my first row is like all following ones. Is this possible?

Example table I would like NOT to have a bold first row:
<img width="526" alt="Screenshot 2019-12-23 at 22 24 41" src="https://user-images.githubusercontent.com/5467859/71381370-85b85a00-25d3-11ea-98c7-246906a790cc.png">

**Comment by tcnh** [comment]
bootstrap-plus 2.0.4 doesn't show the bold first row when the actual first row is hidden (like in comment tables, or explicitly by prefixing the first row with a - (minus)
