### ISSUE TITLE
Show indicator in sitebar when page is symlinked

### ISSUE THREAD

**Issue by joroelev** [praegus/fitnesse-bootstrap-plus-theme#36]
![image](https://user-images.githubusercontent.com/5476742/77320355-b57d1800-6d10-11ea-8dfe-e8682f511ab5.png)

In the regular TOC of FitNesse (right site of the screenshot) a '>' sign indicates that the page has been symlinked. This indication is not shown in de sitebar treeview (left). 

Please add this indication to de sitebar as well.

**Comment by ProgrammingAndPoetry** [comment]
We have added the issues to the backlog of our Trello board

https://trello.com/c/jkoRLPRn/215-symlinks-in-sidebar

**Comment by tcnh** [comment]
Proposed indication: `class="fa fa-link"` instead of `>`, so we can use more visual indicators if necessary

**Comment by tcnh** [comment]
Added a boolean isSymlink to the tableOfContents responder, so we can determine if a page is a symlink

**Comment by tcnh** [comment]
Closed via: https://github.com/praegus/fitnesse-bootstrap-plus-theme/pull/48
