### ISSUE TITLE
Relocate the context help to the sitebar

### ISSUE THREAD

**Issue by joroelev** [praegus/fitnesse-bootstrap-plus-theme#37]
The context help menu is currently located in the right upper corner when a page is in edit mode. In order to increase consistency it could be relocated to the sitebar.

![image](https://user-images.githubusercontent.com/5476742/77322529-283bc280-6d14-11ea-901e-bb67edaca68f.png)

**Comment by ProgrammingAndPoetry** [comment]
We have added the issues to the backlog of our Trello board

https://trello.com/c/64r2twsa/214-context-help-naar-sidebar

**Comment by tcnh** [comment]
Styling of context help is sidebar like now, but resides on the right. Closing this
