### ISSUE TITLE
No treeview shown in sitebar when on root page

### ISSUE THREAD

**Issue by joroelev** [praegus/fitnesse-bootstrap-plus-theme#38]
When on the FitNesse root page (E.g. localhost:9090/root) no treeview is shown in the sitebar. 

Steps to reproduce:
1. Navigate to the /root page of a FitNesse instance with bootstrap plus theme version >= 2.0.5 installed. Observe that pages are shown in de TOC on the page.
2. Try to expand the FitNesseRoot node in the sidebar

Actual result: no subpage are shown in the sitebar
Expected result: subpage are shown in the sitebar.

![image](https://user-images.githubusercontent.com/5476742/77324511-29222380-6d17-11ea-9646-976af9924a4f.png)

**Comment by ProgrammingAndPoetry** [comment]
We have added the issues to the backlog of our Trello board

https://trello.com/c/iPc4pz5I/213-bug-geen-sidebar

**Comment by Lizzze** [comment]
This issue is fixed, this will be present in the next release.

**Comment by tcnh** [comment]
Fixed in PR#43
