### ISSUE TITLE
i would like to filter setups and teardowns from Recent Test History

### ISSUE THREAD

**Issue by ywevanderpol** [praegus/fitnesse-bootstrap-plus-theme#41]
on the root page in the recent test history it also shows my suiteteardown. I would like to filter "special pages" from this overview:

![image](https://user-images.githubusercontent.com/24470599/77513692-c1361f00-6e75-11ea-8ff9-7ba231c8f7e0.png)

**Comment by Lizzze** [comment]
We have added the issues to the backlog of our Trello board

https://trello.com/c/9mPBcEam/

**Comment by tcnh** [comment]
Fixed in https://github.com/praegus/toolchain-fitnesse-plugin/releases/tag/toolchain-fitnesse-plugin-2.0.10
