### ISSUE TITLE
I would like to see the pages treeview in the sidebar instead of a spinner when a test or suite is being run

### ISSUE THREAD

**Issue by joroelev** [praegus/fitnesse-bootstrap-plus-theme#42]
If a suite or testpage is being executed, a spinner (fitnesse logo) is shown in the sidebar.  No treeview is visible. I would like to see the treeview when a test or suite is being run.

![image](https://user-images.githubusercontent.com/5476742/77550733-bc8f5c00-6eb1-11ea-8c24-96ba7b066b09.png)

**Comment by Lizzze** [comment]
We have added the issue to the backlog of our Trello board but with a different fix.

https://trello.com/c/KP12ehrZ/

**Comment by Lizzze** [comment]
This issue has been fixed and can be closed

**Comment by tcnh** [comment]
Running tests no longer display the sidebar
