### ISSUE TITLE
I would like to be able to view page tags in the sidebar

### ISSUE THREAD

**Issue by joroelev** [praegus/fitnesse-bootstrap-plus-theme#44]
Page tags are currently not visible in the sidebar, but it would be useful to have the possibility to show the tags. 

A nice solutions would be to create an extra toggle in the sidebar that enables users to show/hide the tags.

**Comment by Lizzze** [comment]
We have added the issues to the backlog of our Trello board

https://trello.com/c/YxDDpYFu/

**Comment by tcnh** [comment]
Toggle now exists
