### ISSUE TITLE
Make (Suite)SetUp/TearDown pages easily recognizable in sidebar by giving them their own icon 

### ISSUE THREAD

**Issue by joroelev** [praegus/fitnesse-bootstrap-plus-theme#63]
(Suite)SetUp and (Suite)TearDown pages are shown in the sidebar with the static page icon. To make this sites more easily recognizable it would be nice if they got their own icon.

![image](https://user-images.githubusercontent.com/5476742/81294930-e1115300-906f-11ea-8701-34469794504c.png)

**Comment by tcnh** [comment]
Fixed in https://github.com/praegus/fitnesse-bootstrap-plus-theme/releases/tag/fitnesse-bootstrap-plus-theme-2.0.12
