### ISSUE TITLE
Create keyboard shortcuts for opening and closing of sidebar/context help panels

### ISSUE THREAD

**Issue by joroelev** [praegus/fitnesse-bootstrap-plus-theme#66]
Currently the sidebar and conext help panels can only be opened closed with a mouse click. Being able to do so using a keyboard shortcut would be helpful.

**Comment by tcnh** [comment]
What would be logical shortcuts?

**Comment by tcnh** [comment]
https://github.com/praegus/fitnesse-bootstrap-plus-theme/releases/tag/fitnesse-bootstrap-plus-theme-2.0.12 (Alt+1/Alt+2)
