### ISSUE TITLE
Add url from mvn repo to release notes

### ISSUE THREAD

**Issue by ywevanderpol** [praegus/fitnesse-bootstrap-plus-theme#71]
currently there are a few release notes in the version checker. But not all. Is it possible to add the mvn repo link in the release notes section automatically.

![image](https://user-images.githubusercontent.com/24470599/96549934-76b43e00-12b0-11eb-994b-c06bca1a6213.png)

for example:
![image](https://user-images.githubusercontent.com/24470599/96550007-93507600-12b0-11eb-93cb-07acd583cc3a.png)

Then at least you can navigate to the project to see what might be changed

**Comment by tcnh** [comment]
Fixed in https://github.com/praegus/fitnesse-bootstrap-plus-theme/releases/tag/fitnesse-bootstrap-plus-theme-2.0.12
