### ISSUE TITLE
Feature request: make sidebar keyboard accessible by keyboard

### ISSUE THREAD

**Issue by joroelev** [praegus/fitnesse-bootstrap-plus-theme#74]
The page tree shown in the sidebar is currently not accessible by keyboard. It would be nice to be able to select and open pages using the keyboard.

**Comment by tcnh** [comment]
Fixed: https://github.com/praegus/fitnesse-bootstrap-plus-theme/commit/a1957a3d95c59d7b500207b7251af06bcdcd3cab
